# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thawts < Formula
  desc "Thought capture and review — CLI/TUI mode"
  homepage "https://thawts.app"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/thawts/thawts/releases/download/v0.1.2/thawts_darwin_amd64.zip"
    sha256 "9fb12afd6d8e3ed0bfe44ec3b8a45860e3b508452c45aaa86edb1b5f801812b6"

    define_method(:install) do
      bin.install "thawts"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/thawts/thawts/releases/download/v0.1.2/thawts_darwin_arm64.zip"
    sha256 "e9cc51dd0aa4f0ecb13ea01bc2709fc1cd9ea9bbe645d0bba0005fd10574fe6a"

    define_method(:install) do
      bin.install "thawts"
    end
  end

  test do
    system "#{bin}/thawts", "--version"
  end
end
