# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thawts < Formula
  desc "Thought capture and review — CLI/TUI mode"
  homepage "https://thawts.app"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/thawts/thawts/releases/download/v0.1.2/thawts_darwin_amd64.zip"
    sha256 "8cc08f06f3f3cbed85705c86f4c51521bc1459972228003141924d57ac1505a5"

    define_method(:install) do
      bin.install "thawts"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/thawts/thawts/releases/download/v0.1.2/thawts_darwin_arm64.zip"
    sha256 "b5a8ba74b360c831b627ed32ba51def430b61090aeecbf76e383c7decd746d1f"

    define_method(:install) do
      bin.install "thawts"
    end
  end

  test do
    system "#{bin}/thawts", "--version"
  end
end
