# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thawts < Formula
  desc "Thought capture and review — CLI/TUI mode"
  homepage "https://thawts.app"
  version "0.1.8"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/thawts/thawts/releases/download/v0.1.8/thawts_darwin_arm64.zip"
    sha256 "d96c7d7f4779d5d800730208fb10666a2b393eb0981286d7bbbe0dd1c0033579"

    define_method(:install) do
      bin.install "thawts"
    end
  end

  test do
    system "#{bin}/thawts", "--version"
  end
end
